var GAME_LEVELS = [
  ["                       v                     v                v                 ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                           o    ",
   "                                                                                ",
   "                                                                         xxxxx  ",
   "                                                                  xxxx  pxxxxx  ",
   "                             xxxxxx                      xxxxxx          xxxxx  ",
   "                   |         x    x              xxxxx                   xxxxx  ",
   "           t       xxxxxx    x    x   xxxxxxxx   xxxxx                   xxxxx  ",
   "            xxx    x    x    x    x              xxxxx                   xxxxx  ",
   "     @    p        x    x    x    xp            pxxxxx           xxxxx   xxxxx  ",
   "!!xxxxxxx!!!!!!!xxxx    x!!!!x    x!!!!!!!!!!!!!xxxxxx !!! xxxxxxx!!!xxxxxxxxx  ",
   "!!!!!!!!x!!!!!!!x       x!!!!x    x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ",
   "!!!!!!!!xxxxxxxxx       xxxxxx    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["v v        v      v       v               |         x                                                             ",
   "     @                                      xxx     x                                                             ",
   "                                       xxx    x     | xxxxx                                                       ",
   "                              t               x        |   |                                                      ",
   "                     xxx  xxxxxxxxxxx         x                          t     x                                  ",
   "        xxxx       xxx    p                   x     xxxxx   xxxx   xxx                                            ",
   "        v         x                        xxxx   xxx    xxx                                                      ",
   "              xxx                                                                                t        p       ",
   "                |                                                                         xxxxxxxxxxxxxxxxxxxxx   ",
   "                                                                                                    v     v       ",
   "                                                  xxx                                                             ",
   "      xxxx     xxxxxxxxx                       x!!!!!x                                        xx                  ",
   "                                               xv   vx                           x x         x x                  ",
   "     |                                         x     x                             x         x                    ",
   "     xxxx                                      x     x                             xx        x                    ",
   "                                               x     x                             x         |                    ",
   "                  |                            x     x               x  |x         x                              ",
   "               xxxxxxx        xxx   xxx        x     x               x|  x         x                              ",
   "                                                                                                                  ",
   "                                                                                                                  ",
   "                                         xxxx  xxxxxxx        xxx                        xxxx                     ",
   "                                     xxx                xxx p                      xxxx         xxxx            o ",
   "                       |  |  t      p             |       |        xxxxx xx        x  x                xxxxx  p   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx!!!!!!                          xxxxxxxxx  x        |              xxxx",
   "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx! x     !!!!!!!!!!!!!!!!!!!!!!",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx !                  xxxxx!!!!!!xxxxxxxxxxxxxxxxxxxxx",
   "!!!!x x!!!!!!x                                                                      x                             ",
   "!!!!x x!!!!!!x                                                                       xx                           ",
   "!!!!x x!!!!!!x                                                                         x                          ",
   "!!!!x x!!!!!!x                                                                          xxxxxxxxxxxxxxxxxxxxxx    "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                            xxxxxxxxxxxx       xxx                            ",
   "                                                                 v                                            ",
   "                                                                                                              ",
   "                                                      x    v               x!!!x                              ",
   "                                                                                                              ",
   "                               v                                                                              ",
   "                                                                                                              ",
   " xxxxxxxxxxxxxxxxxxxxxxxx                                                                                     ",
   "          |   v                                                                                               ",
   "                                                           xxxxx                       |                      ",
   "                                                           x    x                     txxxx                   ",
   "                               xx     x   x  t   x    x    x     xx          xxx p  xx!!!!!x                  ",
   "                             xx!!!!!!!!!!!!xp   p     !!!!!!!!!!!!!!!xxxx             v       x               ",
   "                             x xxxvx x xxx x          x!!!!!!!!!!!!!!x                      x                 ",
   "    o                        x             x!!!!!!xxxx!xxxxxx!xxxxxxx               xxxxxpxx                 ",
   "        x| xxx    xx    xxxxxxx           xx!!!!!x     v      v                 |  x                          ",
   "  xxxxxx!!!!!!!!!!!!!!!!!!!!!!x           x!!!!!!x                              xxxx                     xxx  ",
   "  x x  x!!!!!!!!!!!!!!!!!!!!!!x           x!!!!!!x                            t                          x x  ",
   "  x xxxxxxxxv  xxxxxxxxxxxxxx x           xxxxxxxx           t  xxxxxxxxxxxxxx                             x  ",
   "  x     |                     x           xv  v                          x!!!x                             x  ",
   "  x                                                        xxxx          x x x                             x  ",
   "  x                                                        x  xx!!!!!!!!!!!!!!                             x  ",
   "  x                                       t         | xxxxxx                                               x  ",
   "  x     @         x                       xxxxxxxxxx                                             x         x  ",
   "  x t  xxxx                            | x            p    p                                              x  ",
   "  x  t x  xxx   xxxxxx        xxxxxxxxxxxxx                                                                x  ",
   "  xt   x  x!!!!!p!!!x t  p    x           x                                                                   ",
   "  xxxxx   x xxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxx     xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                              ",
   "                                                                                                              "],
  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                         x     x                                              ",
   "                                                    xxx  xx    x                                              ",
   "      x   x      xxx    x   x       x           x    x   x x   x                                              ",
   "       x x      x   x   x   x        x    x    x     x   x  x  x                                              ",
   "        x       x   x   x   x         x  x x  x      x   x   x x                                              ",
   "        x        xxx     xxx           x    x       xxx  x    xx                                              ",
   "        x                                                                                                     ",
   "                                                                                                              ",
   "     @                                                                                                        ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx     ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                      xx                                                      ",
   "                   xxx         xxx                                                                            ",
   "                                                                                                              ",
   "                          o                                                     x      x                      ",
   "                                                          xx     xx                                           ",
   "             xxx         xxx         xxx                                 x                  x                 ",
   "                                                                                                              ",
   "                                                                 ||                                           ",
   "                                                                                                              ",
   "                xxxxxxxxx o xxxxxxxxx o xx                                                x                   ",
   "                x       x   x       x   x                 ||                  x     x                         ",
   "                                o   xxxxx                                                                     ",
   "  xxxxxxx                                     xxxxx       xx     xx     xxx                                   ",
   "        x=                  =                =x   x                     xxx                                   ",
   "        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx   x!!!!!!!!!!!!!!!!!!!!!xxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!",
   "                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
